Website = "https://github.com/abakum/crocson/releases"

[Details]
Icon = "res/mipmap-xxxhdpi-v4/icon.png"
Name = "crocson"
ID = "com.github.abakum.crocson"
Version = "1.11.62"
Build = 1940

[Source]
Repo = "https://github.com/abakum/crocson"

[LinuxAndBSD]
GenericName = "GUI for croc"
Categories = ["Network", "FileTransfer", "Telephony", "Security"]
Comment = "A simple GUI for croc"
