Website = "https://github.com/abakum/crocson/releases"

[Details]
Icon = "res/mipmap-xxxhdpi-v4/icon.png"
Name = "crocson"
ID = "com.github.abakum.crocson"
Version = "1.11.74"
Build = 1996

[Source]
Repo = "https://github.com/abakum/crocson"

[LinuxAndBSD]
GenericName = "GUI for croc"
Categories = ["Network", "FileTransfer", "Telephony", "Security"]
Comment = "A simple GUI for croc"
Keywords = ["croc", "fyne", "p2p", "webdav", "webchat", "gui", "cli", "magic-wormhole", "webwormhole", "qr", "media-recording", "screen-sharing"]
